# Resolução dos exercícios: transformação de dados com pandas

**Autor:** Victor Henriques, Ph.D.

Este notebook consolida as respostas dos 14 exercícios propostos para a base `flights`. Os códigos priorizam operações vetorizadas, pipelines curtos e boas práticas de análise de dados.

> Convenções: atrasos são medidos em minutos, `distance` em milhas e `air_time` em minutos.

## Preparação do ambiente e carregamento dos dados

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid", context="talk")
pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 140)

url = "https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/flights/flights.csv"
flights = pd.read_csv(url)
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

# 1. Filtragem de voos

Cada item abaixo utiliza uma condição específica. O método `query()` é apropriado quando a expressão é curta e legível; `isin()` é especialmente útil para testar pertencimento a um conjunto de valores.

### 1.1 Voos com atraso de chegada de duas horas ou mais

In [4]:
flights.query("arr_delay >= 120")

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
119,2013,1,1,811.0,630,101.0,1047.0,830,137.0,MQ,4576,N531MQ,LGA,CLT,118.0,544,6,30,2013-01-01T11:00:00Z
151,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,MQ,3944,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01T23:00:00Z
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
447,2013,1,1,1505.0,1310,115.0,1638.0,1431,127.0,EV,4497,N17984,EWR,RIC,63.0,277,13,10,2013-01-01T18:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z
336668,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,EV,4294,N13988,EWR,SAV,95.0,708,16,49,2013-09-30T20:00:00Z
336724,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,EV,5292,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30T22:00:00Z
336757,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30T22:00:00Z
336763,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,2013-10-01T00:00:00Z

A condição mantém os voos cujo atraso de chegada é igual ou superior a 120 minutos.

### 1.2 Voos para Houston, `IAH` ou `HOU`

In [7]:
flights[flights["dest"].isin(["IAH", "HOU"])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
32,2013,1,1,623.0,627,-4.0,933.0,932,1.0,UA,496,N459UA,LGA,IAH,229.0,1416,6,27,2013-01-01T11:00:00Z
81,2013,1,1,728.0,732,-4.0,1041.0,1038,3.0,UA,473,N488UA,LGA,IAH,238.0,1416,7,32,2013-01-01T12:00:00Z
89,2013,1,1,739.0,739,0.0,1104.0,1038,26.0,UA,1479,N37408,EWR,IAH,249.0,1400,7,39,2013-01-01T12:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336524,2013,9,30,1729.0,1720,9.0,2001.0,2010,-9.0,UA,652,N455UA,EWR,IAH,173.0,1400,17,20,2013-09-30T21:00:00Z
336527,2013,9,30,1735.0,1715,20.0,2010.0,2005,5.0,WN,2067,N296WN,EWR,HOU,188.0,1411,17,15,2013-09-30T21:00:00Z
336618,2013,9,30,1859.0,1859,0.0,2134.0,2159,-25.0,UA,1128,N14731,LGA,IAH,180.0,1416,18,59,2013-09-30T22:00:00Z
336694,2013,9,30,2015.0,2015,0.0,2244.0,2307,-23.0,UA,1545,N17730,EWR,IAH,174.0,1400,20,15,2013-10-01T00:00:00Z
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z

`isin()` retorna `True` quando o destino pertence à lista informada.

### 1.3 Voos operados por United, American ou Delta

In [9]:
flights[flights["carrier"].isin(["UA", "AA", "DL"])]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z
5,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,2013-01-01T10:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336737,2013,9,30,2105.0,2106,-1.0,2329.0,2354,-25.0,UA,475,N477UA,EWR,IAH,175.0,1400,21,6,2013-10-01T01:00:00Z
336744,2013,9,30,2121.0,2100,21.0,2349.0,14,-25.0,DL,2363,N193DN,JFK,LAX,296.0,2475,21,0,2013-10-01T01:00:00Z
336751,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,2013-10-01T01:00:00Z
336755,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,2013-10-01T01:00:00Z
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z

Os códigos utilizados na base são `UA`, `AA` e `DL`.

### 1.4 Voos que partiram em julho, agosto ou setembro

In [11]:
flights[flights["month"].between(7, 9)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
250450,2013,7,1,1.0,2029,212.0,236.0,2359,157.0,B6,915,N653JB,JFK,SFO,315.0,2586,20,29,2013-07-02T00:00:00Z
250451,2013,7,1,2.0,2359,3.0,344.0,344,0.0,B6,1503,N805JB,JFK,SJU,200.0,1598,23,59,2013-07-02T03:00:00Z
250452,2013,7,1,29.0,2245,104.0,151.0,1,110.0,B6,234,N348JB,JFK,BTV,66.0,266,22,45,2013-07-02T02:00:00Z
250453,2013,7,1,43.0,2130,193.0,322.0,14,188.0,B6,1371,N794JB,LGA,FLL,143.0,1076,21,30,2013-07-02T01:00:00Z
250454,2013,7,1,44.0,2150,174.0,300.0,100,120.0,AA,185,N324AA,JFK,LAX,297.0,2475,21,50,2013-07-02T01:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

`between(7, 9)` inclui os limites e seleciona os meses 7, 8 e 9.

### 1.5 Voos que chegaram mais de duas horas atrasados, mas não partiram atrasados

In [13]:
flights.query("arr_delay > 120 and dep_delay <= 0")

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
22911,2013,1,27,1419.0,1420,-1.0,1754.0,1550,124.0,MQ,3728,N1EAMQ,EWR,ORD,135.0,719,14,20,2013-01-27T19:00:00Z
33011,2013,10,7,1350.0,1350,0.0,1736.0,1526,130.0,EV,5181,N611QX,LGA,MSN,117.0,812,13,50,2013-10-07T17:00:00Z
33019,2013,10,7,1357.0,1359,-2.0,1858.0,1654,124.0,AA,1151,N3CMAA,LGA,DFW,192.0,1389,13,59,2013-10-07T17:00:00Z
41075,2013,10,16,657.0,700,-3.0,1258.0,1056,122.0,B6,3,N703JB,JFK,SJU,225.0,1598,7,0,2013-10-16T11:00:00Z
55985,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,399,N629VA,JFK,LAX,336.0,2475,7,0,2013-11-01T11:00:00Z
152766,2013,3,18,1844.0,1847,-3.0,39.0,2219,140.0,UA,389,N560UA,JFK,SFO,386.0,2586,18,47,2013-03-18T22:00:00Z
180893,2013,4,17,1635.0,1640,-5.0,2049.0,1845,124.0,MQ,4540,N721MQ,LGA,DTW,130.0,502,16,40,2013-04-17T20:00:00Z
181270,2013,4,18,558.0,600,-2.0,1149.0,850,179.0,AA,707,N3EXAA,LGA,DFW,234.0,1389,6,0,2013-04-18T10:00:00Z
181327,2013,4,18,655.0,700,-5.0,1213.0,950,143.0,AA,2083,N565AA,EWR,DFW,230.0,1372,7,0,2013-04-18T11:00:00Z
213693,2013,5,22,1827.0,1830,-3.0,2217.0,2010,127.0,MQ,4674,N518MQ,LGA,CLE,90.0,419,18,30,2013-05-22T22:00:00Z
214512,2013,5,23,1810.0,1810,0.0,2208.0,2000,128.0,MQ,4626,N525MQ,LGA,CMH,82.0,479,18,10,2013-05-23T22:00:00Z
226434,2013,6,5,1604.0,1615,-11.0,2041.0,1840,121.0,MQ,4657,N510MQ,LGA,ATL,158.0,762,16,15,2013-06-05T20:00:00Z
235033,2013,6,14,1708.0,1710,-2.0,2227.0,2015,132.0,AA,181,N320AA,JFK,LAX,334.0,2475,17,10,2013-06-14T21:00:00Z
244329,2013,6,24,1602.0,1605,-3.0,2134.0,1916,138.0,DL,706,N3768,JFK,AUS,247.0,1521,16,5,2013-06-24T20:00:00Z
247568,2013,6,27,2052.0,2100,-8.0,13.0,2210,123.0,US,2144,N952UW,LGA,BOS,46.0,184,21,0,2013-06-28T01:00:00Z
249957,2013,6,30,1423.0,1425,-2.0,1816.0,1554,142.0,B6,2402,N206JB,JFK,BUF,80.0,301,14,25,2013-06-30T18:00:00Z
250689,2013,7,1,905.0,905,0.0,1443.0,1223,140.0,DL,1057,N337NB,LGA,MIA,183.0,1096,9,5,2013-07-01T13:00:00Z
256340,2013,7,7,1659.0,1700,-1.0,2050.0,1823,147.0,US,2183,N948UW,LGA,DCA,64.0,214,17,0,2013-07-07T21:00:00Z
256358,2013,7,7,1727.0,1730,-3.0,2203.0,1951,132.0,F9,837,N263AV,LGA,DEN,236.0,1620,17,30,2013-07-07T21:00:00Z
256373,2013,7,7,1746.0,1755,-9.0,2133.0,1921,132.0,B6,1407,N374JB,JFK,IAD,78.0,228,17,55,2013-07-07T21:00:00Z
256405,2013,7,7,1823.0,1830,-7.0,2201.0,1955,126.0,MQ,3486,N724MQ,LGA,BNA,113.0,764,18,30,2013-07-07T22:00:00Z
270742,2013,7,22,1555.0,1600,-5.0,2139.0,1938,121.0,DL,141,N713TW,JFK,SFO,371.0,2586,16,0,2013-07-22T20:00:00Z
270752,2013,7,22,1606.0,1615,-9.0,2056.0,1831,145.0,DL,1619,N970DL,LGA,MSP,140.0,1020,16,15,2013-07-22T20:00:00Z
270762,2013,7,22,1628.0,1630,-2.0,2151.0,1939,132.0,B6,423,N625JB,JFK,LAX,332.0,2475,16,30,2013-07-22T20:00:00Z
276564,2013,7,28,1710.0,1711,-1.0,2248.0,2039,129.0,B6,167,N510JB,JFK,OAK,353.0,2576,17,11,2013-07-28T21:00:00Z
287148,2013,8,8,1457.0,1500,-3.0,1828.0,1624,124.0,US,2185,N746UW,LGA,DCA,70.0,214,15,0,2013-08-08T19:00:00Z
291439,2013,8,13,657.0,659,-2.0,1015.0,814,121.0,EV,4522,N14188,EWR,BNA,146.0,748,6,59,2013-08-13T10:00:00Z
305985,2013,8,28,1157.0,1200,-3.0,1520.0,1316,124.0,US,2179,N737US,LGA,DCA,63.0,214,12,0,2013-08-28T16:00:00Z
325764,2013,9,19,656.0,700,-4.0,1037.0,833,124.0,UA,331,N808UA,LGA,ORD,192.0,733,7,0,2013-09-19T11:00:00Z

A condição combina atraso de chegada superior a 120 minutos com partida no horário ou antecipada.

### 1.6 Voos que partiram pelo menos uma hora atrasados, mas recuperaram mais de 30 minutos

In [15]:
(
    flights
    .assign(gain=lambda d: d["dep_delay"] - d["arr_delay"])
    .query("dep_delay >= 60 and gain > 30")
)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,gain
815,2013,1,1,2205.0,1720,285.0,46.0,2040,246.0,AA,1999,N5DNAA,EWR,MIA,146.0,1085,17,20,2013-01-01T22:00:00Z,39.0
832,2013,1,1,2326.0,2130,116.0,131.0,18,73.0,B6,199,N594JB,JFK,LAS,290.0,2248,21,30,2013-01-02T02:00:00Z,43.0
2286,2013,1,3,1503.0,1221,162.0,1803.0,1555,128.0,UA,551,N835UA,EWR,SFO,320.0,2565,12,21,2013-01-03T17:00:00Z,34.0
2508,2013,1,3,1839.0,1700,99.0,2056.0,1950,66.0,AA,575,N631AA,JFK,EGE,239.0,1747,17,0,2013-01-03T22:00:00Z,33.0
2522,2013,1,3,1850.0,1745,65.0,2148.0,2120,28.0,AA,177,N332AA,JFK,SFO,314.0,2586,17,45,2013-01-03T22:00:00Z,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336572,2013,9,30,1818.0,1715,63.0,2001.0,1940,21.0,9E,3310,N934XJ,JFK,MCI,142.0,1113,17,15,2013-09-30T21:00:00Z,42.0
336579,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,9E,3459,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30T19:00:00Z,37.0
336674,2013,9,30,1956.0,1825,91.0,2208.0,2121,47.0,DL,1576,N3772H,JFK,SAN,292.0,2446,18,25,2013-09-30T22:00:00Z,44.0
336704,2013,9,30,2028.0,1910,78.0,2255.0,2215,40.0,AA,21,N338AA,JFK,LAX,294.0,2475,19,10,2013-09-30T23:00:00Z,38.0
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z,38.0

Definimos `gain = dep_delay - arr_delay`. Um valor positivo indica que parte do atraso foi recuperada; `gain > 30` significa recuperação superior a 30 minutos.

# 2. Voos com os maiores atrasos de partida

In [17]:
(
    flights
    .nlargest(10, "dep_delay")
    [["year", "month", "day", "carrier", "flight", "origin", "dest", "dep_delay"]]
)

        year  month  day carrier  flight origin dest  dep_delay
7072    2013      1    9      HA      51    JFK  HNL     1301.0
235778  2013      6   15      MQ    3535    JFK  CMH     1137.0
8239    2013      1   10      MQ    3695    EWR  ORD     1126.0
327043  2013      9   20      AA     177    JFK  SFO     1014.0
270376  2013      7   22      MQ    3075    JFK  CVG     1005.0
173992  2013      4   10      DL    2391    JFK  TPA      960.0
151974  2013      3   17      DL    2119    LGA  MSP      911.0
247040  2013      6   27      DL    2007    JFK  PDX      899.0
270987  2013      7   22      DL    2047    LGA  ATL      898.0
87238   2013     12    5      AA     172    EWR  MIA      896.0

`nlargest()` é uma forma curta e expressiva de retornar as linhas com os maiores valores de uma coluna.

# 3. Voos mais rápidos

In [19]:
fastest_flights = (
    flights
    .dropna(subset=["distance", "air_time"])
    .assign(speed_mph=lambda d: d["distance"] / d["air_time"] * 60)
    .nlargest(10, "speed_mph")
)

fastest_flights[
    ["carrier", "flight", "origin", "dest", "distance", "air_time", "speed_mph"]
]

       carrier  flight origin dest  distance  air_time   speed_mph
216447      DL    1499    LGA  ATL       762      65.0  703.384615
251999      EV    4667    EWR  MSP      1008      93.0  650.322581
205388      EV    4292    EWR  GSP       594      55.0  648.000000
157516      EV    3805    EWR  BNA       748      70.0  641.142857
10223       DL    1902    LGA  PBI      1035     105.0  591.428571
70640       DL     315    JFK  SJU      1598     170.0  564.000000
129835      B6     707    JFK  SJU      1598     172.0  557.441860
70704       AA     936    JFK  STT      1623     175.0  556.457143
70551       DL     347    JFK  SJU      1598     173.0  554.219653
70588       B6    1503    JFK  SJU      1598     173.0  554.219653

A velocidade média é calculada em milhas por hora. A multiplicação por 60 converte milhas por minuto em milhas por hora. Como valores extremos podem resultar de tempos de voo muito pequenos ou registros anômalos, eles devem ser investigados antes de qualquer conclusão substantiva.

# 4. Voos que viajaram mais longe

In [21]:
flights.loc[
    flights["distance"].eq(flights["distance"].max()),
    ["carrier", "flight", "origin", "dest", "distance"],
]

       carrier  flight origin dest  distance
162         HA      51    JFK  HNL      4983
1073        HA      51    JFK  HNL      4983
2018        HA      51    JFK  HNL      4983
2922        HA      51    JFK  HNL      4983
3791        HA      51    JFK  HNL      4983
...        ...     ...    ...  ...       ...
331506      HA      51    JFK  HNL      4983
333478      HA      51    JFK  HNL      4983
334406      HA      51    JFK  HNL      4983
335095      HA      51    JFK  HNL      4983
336081      HA      51    JFK  HNL      4983

[342 rows x 5 columns]

A comparação com o valor máximo preserva todos os voos empatados na maior distância, ao contrário de uma seleção arbitrária de apenas uma linha.

# 5. A ordem entre `query()` e `sort_values()` importa?

In [23]:
resultado_1 = (
    flights
    .query("dep_delay > 60")
    .sort_values("arr_delay", ascending=False)
)

resultado_2 = (
    flights
    .sort_values("arr_delay", ascending=False)
    .query("dep_delay > 60")
)

resultado_1.equals(resultado_2)

False

Quando o filtro não depende da posição das linhas, os dois pipelines tendem a produzir as mesmas linhas na mesma ordem. Entretanto, filtrar primeiro costuma ser mais eficiente, pois reduz o número de linhas que precisam ser ordenadas.

A equivalência deixa de valer quando há uma seleção por quantidade ou posição entre as operações. Por exemplo, “filtrar entre os dez maiores atrasos gerais” não é igual a “encontrar os dez maiores atrasos entre os voos filtrados”.

In [25]:
# Dez maiores atrasos gerais, seguidos do filtro
flights.nlargest(10, "arr_delay").query("dep_delay > 60")

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09T14:00:00Z
235778,2013,6,15,1432.0,1935,1137.0,1607.0,2120,1127.0,MQ,3535,N504MQ,JFK,CMH,74.0,483,19,35,2013-06-15T23:00:00Z
8239,2013,1,10,1121.0,1635,1126.0,1239.0,1810,1109.0,MQ,3695,N517MQ,EWR,ORD,111.0,719,16,35,2013-01-10T21:00:00Z
327043,2013,9,20,1139.0,1845,1014.0,1457.0,2210,1007.0,AA,177,N338AA,JFK,SFO,354.0,2586,18,45,2013-09-20T22:00:00Z
270376,2013,7,22,845.0,1600,1005.0,1044.0,1815,989.0,MQ,3075,N665MQ,JFK,CVG,96.0,589,16,0,2013-07-22T20:00:00Z
173992,2013,4,10,1100.0,1900,960.0,1342.0,2211,931.0,DL,2391,N959DL,JFK,TPA,139.0,1005,19,0,2013-04-10T23:00:00Z
151974,2013,3,17,2321.0,810,911.0,135.0,1020,915.0,DL,2119,N927DA,LGA,MSP,167.0,1020,8,10,2013-03-17T12:00:00Z
270987,2013,7,22,2257.0,759,898.0,121.0,1026,895.0,DL,2047,N6716C,LGA,ATL,109.0,762,7,59,2013-07-22T11:00:00Z
87238,2013,12,5,756.0,1700,896.0,1058.0,2020,878.0,AA,172,N5DMAA,EWR,MIA,149.0,1085,17,0,2013-12-05T22:00:00Z
195711,2013,5,3,1133.0,2055,878.0,1250.0,2215,875.0,MQ,3744,N523MQ,EWR,ORD,112.0,719,20,55,2013-05-04T00:00:00Z

In [27]:
# Dez maiores atrasos somente entre os voos filtrados
flights.query("dep_delay > 60").nlargest(10, "arr_delay")

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
7072,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,HA,51,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09T14:00:00Z
235778,2013,6,15,1432.0,1935,1137.0,1607.0,2120,1127.0,MQ,3535,N504MQ,JFK,CMH,74.0,483,19,35,2013-06-15T23:00:00Z
8239,2013,1,10,1121.0,1635,1126.0,1239.0,1810,1109.0,MQ,3695,N517MQ,EWR,ORD,111.0,719,16,35,2013-01-10T21:00:00Z
327043,2013,9,20,1139.0,1845,1014.0,1457.0,2210,1007.0,AA,177,N338AA,JFK,SFO,354.0,2586,18,45,2013-09-20T22:00:00Z
270376,2013,7,22,845.0,1600,1005.0,1044.0,1815,989.0,MQ,3075,N665MQ,JFK,CVG,96.0,589,16,0,2013-07-22T20:00:00Z
173992,2013,4,10,1100.0,1900,960.0,1342.0,2211,931.0,DL,2391,N959DL,JFK,TPA,139.0,1005,19,0,2013-04-10T23:00:00Z
151974,2013,3,17,2321.0,810,911.0,135.0,1020,915.0,DL,2119,N927DA,LGA,MSP,167.0,1020,8,10,2013-03-17T12:00:00Z
270987,2013,7,22,2257.0,759,898.0,121.0,1026,895.0,DL,2047,N6716C,LGA,ATL,109.0,762,7,59,2013-07-22T11:00:00Z
87238,2013,12,5,756.0,1700,896.0,1058.0,2020,878.0,AA,172,N5DMAA,EWR,MIA,149.0,1085,17,0,2013-12-05T22:00:00Z
195711,2013,5,3,1133.0,2055,878.0,1250.0,2215,875.0,MQ,3744,N523MQ,EWR,ORD,112.0,719,20,55,2013-05-04T00:00:00Z

# 6. Comparação entre `air_time` e `arr_time - dep_time`

In [29]:
flights.assign(
    naive_duration=lambda d: d["arr_time"] - d["dep_time"]
)[["dep_time", "arr_time", "air_time", "naive_duration"]].head()

   dep_time  arr_time  air_time  naive_duration
0     517.0     830.0     227.0           313.0
1     533.0     850.0     227.0           317.0
2     542.0     923.0     160.0           381.0
3     544.0    1004.0     183.0           460.0
4     554.0     812.0     116.0           258.0

A subtração direta não funciona corretamente porque `dep_time` e `arr_time` são números no formato HHMM, não quantidades de minutos. Por exemplo, `1030 - 945` produz 85, embora a diferença entre 09:45 e 10:30 seja 45 minutos.

Além disso, alguns voos atravessam a meia-noite, origem e destino podem usar fusos horários diferentes, e `air_time` mede apenas o tempo no ar, enquanto a diferença entre chegada e partida inclui outras etapas operacionais.

In [31]:
def hhmm_to_minutes(time):
    """Converte um horário numérico HHMM em minutos após a meia-noite."""
    return (time // 100) * 60 + time % 100

comparison = (
    flights
    .dropna(subset=["dep_time", "arr_time", "air_time"])
    .assign(
        dep_minutes=lambda d: hhmm_to_minutes(d["dep_time"]),
        arr_minutes=lambda d: hhmm_to_minutes(d["arr_time"]),
    )
    .assign(
        clock_elapsed=lambda d: (d["arr_minutes"] - d["dep_minutes"]) % 1440
    )
)

comparison[["dep_time", "arr_time", "air_time", "clock_elapsed"]].head()

   dep_time  arr_time  air_time  clock_elapsed
0     517.0     830.0     227.0          193.0
1     533.0     850.0     227.0          197.0
2     542.0     923.0     160.0          221.0
3     544.0    1004.0     183.0          260.0
4     554.0     812.0     116.0          138.0

Mesmo depois da conversão, `clock_elapsed` não precisa ser igual a `air_time`. Uma comparação rigorosa exigiria datetimes completos, fusos horários dos aeroportos e conversão para uma referência temporal comum, como UTC.

# 7. Relação entre `dep_time`, `sched_dep_time` e `dep_delay`

Em princípio, `dep_delay` corresponde à diferença, em minutos, entre o horário real e o horário programado de partida. Valores positivos indicam atraso, zero indica partida no horário e valores negativos indicam partida antecipada.

In [33]:
departure_check = (
    flights
    .dropna(subset=["dep_time", "sched_dep_time", "dep_delay"])
    .assign(
        actual=lambda d: hhmm_to_minutes(d["dep_time"]),
        scheduled=lambda d: hhmm_to_minutes(d["sched_dep_time"]),
    )
    .assign(
        calculated_delay=lambda d: (d["actual"] - d["scheduled"] + 720) % 1440 - 720
    )
)

departure_check[
    ["dep_time", "sched_dep_time", "dep_delay", "calculated_delay"]
].head()

   dep_time  sched_dep_time  dep_delay  calculated_delay
0     517.0             515        2.0               2.0
1     533.0             529        4.0               4.0
2     542.0             540        2.0               2.0
3     544.0             545       -1.0              -1.0
4     554.0             600       -6.0              -6.0

In [35]:
(
    departure_check
    .assign(difference=lambda d: d["dep_delay"] - d["calculated_delay"])
    ["difference"]
    .value_counts()
    .head()
)

difference
0.0       328492
1440.0        29
Name: count, dtype: int64

A normalização modular trata melhor horários próximos da meia-noite e permite verificar se a diferença calculada coincide com `dep_delay`.

# 8. Formas de selecionar `dep_time`, `dep_delay`, `arr_time` e `arr_delay`

In [ ]:
cols = ["dep_time", "dep_delay", "arr_time", "arr_delay"]

### 8.1 Lista de nomes

In [ ]:
flights[cols].head()

### 8.2 Com `.loc`

In [ ]:
flights.loc[:, cols].head()

### 8.3 Com posições e `.iloc`

In [ ]:
flights.iloc[:, [3, 5, 6, 8]].head()

A seleção por posição é menos robusta, pois depende da ordem atual das colunas.

### 8.4 Com `filter()`

In [ ]:
flights.filter(items=cols).head()

### 8.5 Com expressão regular

In [ ]:
flights.loc[:, flights.columns.str.contains(r"^(dep|arr)_(time|delay)$", regex=True)].head()

### 8.6 Com `isin()`

In [ ]:
flights.loc[:, flights.columns.isin(cols)].head()

`isin()` preserva a ordem original das colunas no DataFrame, não necessariamente a ordem da lista `cols`. Quando os nomes são conhecidos, `flights[cols]` é a solução mais clara.

# 9. Repetição de nomes em uma seleção

In [ ]:
flights[["dep_time", "dep_time", "arr_time"]].head()

In [ ]:
flights.iloc[[0, 0, 1]]

O pandas não remove duplicidades automaticamente. Repetir um nome ou posição repete a coluna ou linha correspondente no resultado. Colunas duplicadas podem tornar seleções posteriores ambíguas, pois selecionar aquele nome pode retornar várias colunas.

# 10. O que faz `.isin()`?

In [ ]:
mask = flights.columns.isin(
    ["year", "month", "day", "dep_delay", "arr_delay"]
)

pd.Series(mask, index=flights.columns)

In [ ]:
flights.loc[:, mask].head()

`flights.columns` contém os nomes das colunas. `isin()` compara cada nome com a lista e retorna uma máscara booleana: `True` para nomes presentes e `False` para os demais. A máscara pode ser usada para selecionar as colunas correspondentes.

# 11. Sensibilidade a maiúsculas e minúsculas em `str.contains()`

In [ ]:
flights.loc[:, flights.columns.str.contains("TIME")]

Por padrão, `str.contains()` diferencia maiúsculas de minúsculas. Como os nomes estão em minúsculas, o padrão `TIME` não encontra correspondências.

In [ ]:
flights.loc[:, flights.columns.str.contains("TIME", case=False, regex=False)].head()

`case=False` ignora a capitalização e `regex=False` informa que o texto deve ser interpretado literalmente, não como expressão regular.

# 12. Qual companhia apresenta os piores atrasos?

A expressão “pior atraso” precisa ser definida. A média é sensível a extremos; a mediana representa melhor o voo típico; e a proporção de atrasos superiores a 15 minutos mede a frequência de atrasos relevantes.

In [ ]:
carrier_delays = (
    flights
    .groupby("carrier", as_index=False)
    .agg(
        flights=("flight", "size"),
        observed_delays=("arr_delay", "count"),
        mean_delay=("arr_delay", "mean"),
        median_delay=("arr_delay", "median"),
        late_share=("arr_delay", lambda x: x.gt(15).mean()),
    )
    .query("observed_delays >= 100")
    .sort_values("mean_delay", ascending=False)
)

carrier_delays

A classificação pode mudar conforme a métrica. Além disso, companhias operam combinações diferentes de origens, destinos, horários e distâncias. Portanto, uma comparação bruta não identifica isoladamente um efeito da companhia.

In [ ]:
carrier_dest = (
    flights
    .groupby(["carrier", "dest"], as_index=False)
    .agg(
        flights=("flight", "size"),
        mean_delay=("arr_delay", "mean"),
    )
    .query("flights >= 30")
)

carrier_dest.head()

In [ ]:
carrier_adjusted = (
    carrier_dest
    .assign(weighted_delay=lambda d: d["mean_delay"] * d["flights"])
    .groupby("carrier", as_index=False)
    .agg(
        weighted_delay=("weighted_delay", "sum"),
        flights=("flights", "sum"),
    )
    .assign(adjusted_mean=lambda d: d["weighted_delay"] / d["flights"])
    .sort_values("adjusted_mean", ascending=False)
)

carrier_adjusted

O agrupamento por companhia e destino reduz parte da diferença de composição, mas não controla completamente origem, horário, mês, distância, congestionamento ou condições meteorológicas. Uma separação mais rigorosa exigiria um modelo estatístico com esses fatores como controles.

# 13. Voo mais atrasado para cada destino

In [ ]:
most_delayed_by_dest = (
    flights
    .dropna(subset=["arr_delay"])
    .loc[lambda d: d.groupby("dest")["arr_delay"].idxmax()]
    .sort_values("arr_delay", ascending=False)
)

most_delayed_by_dest[
    ["dest", "carrier", "flight", "origin", "arr_delay", "year", "month", "day"]
]

`idxmax()` encontra o índice do maior atraso de cada destino. Em caso de empate, retorna apenas a primeira ocorrência.

### Preservando todos os empates

In [ ]:
most_delayed_with_ties = flights.loc[
    flights["arr_delay"].eq(
        flights.groupby("dest")["arr_delay"].transform("max")
    )
].sort_values(["dest", "arr_delay"], ascending=[True, False])

most_delayed_with_ties

# 14. Variação dos atrasos ao longo do dia

In [ ]:
hourly_delays = (
    flights
    .groupby("hour", as_index=False)
    .agg(
        flights=("flight", "size"),
        observed_delays=("dep_delay", "count"),
        mean_dep_delay=("dep_delay", "mean"),
        median_dep_delay=("dep_delay", "median"),
        mean_arr_delay=("arr_delay", "mean"),
        late_share=("dep_delay", lambda x: x.gt(15).mean()),
    )
)

hourly_delays

A análise considera média, mediana, proporção de voos com atraso superior a 15 minutos e quantidade de observações. A média pode ser influenciada por poucos atrasos extremos; a mediana e a proporção oferecem visões complementares.

In [ ]:
sns.lineplot(
    data=hourly_delays,
    x="hour",
    y="mean_dep_delay",
    marker="o",
)

plt.xlabel("Hora programada de partida")
plt.ylabel("Atraso médio na partida, em minutos")
plt.title("Atraso médio ao longo do dia")
plt.show()

### Comparação entre média e mediana

In [ ]:
hourly_long = hourly_delays.melt(
    id_vars="hour",
    value_vars=["mean_dep_delay", "median_dep_delay"],
    var_name="statistic",
    value_name="delay",
)

sns.lineplot(
    data=hourly_long,
    x="hour",
    y="delay",
    hue="statistic",
    marker="o",
)

plt.xlabel("Hora programada de partida")
plt.ylabel("Atraso na partida, em minutos")
plt.title("Média e mediana do atraso ao longo do dia")
plt.show()

O resultado descreve uma associação entre hora programada e atraso. Ele não demonstra, isoladamente, que a hora do dia cause o atraso, pois outras características dos voos também variam ao longo do dia.