In [53]:
import pandas as pd
import numpy as np

In [3]:
url = "https://raw.githubusercontent.com/byuidatascience/data4python4ds/master/data-raw/flights/flights.csv"
flights = pd.read_csv(url)

In [5]:
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [7]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

In [15]:
flights.columns

Index(['year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour'],
      dtype='object')

In [21]:
flights.size

6398744

In [29]:
flights["time_hour"]

0         2013-01-01T10:00:00Z
1         2013-01-01T10:00:00Z
2         2013-01-01T10:00:00Z
3         2013-01-01T10:00:00Z
4         2013-01-01T11:00:00Z
                  ...
336771    2013-09-30T18:00:00Z
336772    2013-10-01T02:00:00Z
336773    2013-09-30T16:00:00Z
336774    2013-09-30T15:00:00Z
336775    2013-09-30T12:00:00Z
Name: time_hour, Length: 336776, dtype: object

In [196]:
df = pd.DataFrame(
    data={
        "col0": [0, 0, 0, 0],
        "col1": [0, 0, 0, 0],
        "col2": [0, 0, 0, 0],
        "col3": ["a", "b", "b", "a"],
        "col4": ["alpha", "gamma", "gamma", "gamma"],
    },
    index=["row" + str(i) for i in range(4)],
)
df.head()

      col0  col1  col2 col3   col4
row0     0     0     0    a  alpha
row1     0     0     0    b  gamma
row2     0     0     0    b  gamma
row3     0     0     0    a  gamma

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, row0 to row3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col0    4 non-null      int64
 1   col1    4 non-null      int64
 2   col2    4 non-null      int64
 3   col3    4 non-null      object
 4   col4    4 non-null      object
dtypes: int64(3), object(2)
memory usage: 192.0+ bytes

In [47]:
flights["time_hour"].head()

0    2013-01-01T10:00:00Z
1    2013-01-01T10:00:00Z
2    2013-01-01T10:00:00Z
3    2013-01-01T10:00:00Z
4    2013-01-01T11:00:00Z
Name: time_hour, dtype: object

In [220]:
df = pd.DataFrame(
    data=np.reshape(range(36), (6, 6)),
    index=["a", "b", "c", "d", "e", "f"],
    columns=["col" + str(i) for i in range(6)],
    dtype=float,
)
df["col6"] = ["apple", "orange", "pineapple", "mango", "kiwi", "lemon"]
df

   col0  col1  col2  col3  col4  col5       col6
a   0.0   1.0   2.0   3.0   4.0   5.0      apple
b   6.0   7.0   8.0   9.0  10.0  11.0     orange
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple
d  18.0  19.0  20.0  21.0  22.0  23.0      mango
e  24.0  25.0  26.0  27.0  28.0  29.0       kiwi
f  30.0  31.0  32.0  33.0  34.0  35.0      lemon

In [59]:
pd.DataFrame(np.reshape(range(36), (6, 6)))

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [218]:
df.iloc[[1]]

   col0  col1  col2  col3  col4  col5    col6
b   6.0   7.0   8.0   9.0  10.0  11.0  orange

In [226]:
df.query(("not col0 == 6"))

   col0  col1  col2  col3  col4  col5       col6
a   0.0   1.0   2.0   3.0   4.0   5.0      apple
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple
d  18.0  19.0  20.0  21.0  22.0  23.0      mango
e  24.0  25.0  26.0  27.0  28.0  29.0       kiwi
f  30.0  31.0  32.0  33.0  34.0  35.0      lemon

In [228]:
flights.query("dep_delay <= 10 and dep_delay >= -10").sort_values("arr_delay", ascending=False).iloc[[0, 1, 2]]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
55985,2013,11,1,658.0,700,-2.0,1329.0,1015,194.0,VX,399,N629VA,JFK,LAX,336.0,2475,7,0,2013-11-01T11:00:00Z
181270,2013,4,18,558.0,600,-2.0,1149.0,850,179.0,AA,707,N3EXAA,LGA,DFW,234.0,1389,6,0,2013-04-18T10:00:00Z
256340,2013,7,7,1659.0,1700,-1.0,2050.0,1823,147.0,US,2183,N948UW,LGA,DCA,64.0,214,17,0,2013-07-07T21:00:00Z

In [135]:
df[["new_column1", "new_column2"]] = [5, 6]
df

   col0  col1  col2  col3  col4  col5       col6  new_column1  new_column2
a   0.0   1.0   2.0   3.0   4.0   5.0      apple            5            6
b   6.0   7.0   8.0   9.0  10.0  11.0     orange            5            6
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple            5            6
d  18.0  19.0  20.0  21.0  22.0  23.0      mango            5            6
e  24.0  25.0  26.0  27.0  28.0  29.0       kiwi            5            6
f  30.0  31.0  32.0  33.0  34.0  35.0      lemon            5            6

In [147]:
df.loc[["a", "b"],["col0","col2"]]

   col0  col2
a   0.0   2.0
b   6.0   8.0

In [155]:
flights.select_dtypes(include = df.loc[:, df.columns.str.startswith("new")].head()"object").head()

  carrier tailnum origin dest             time_hour
0      UA  N14228    EWR  IAH  2013-01-01T10:00:00Z
1      UA  N24211    LGA  IAH  2013-01-01T10:00:00Z
2      AA  N619AA    JFK  MIA  2013-01-01T10:00:00Z
3      B6  N804JB    JFK  BQN  2013-01-01T10:00:00Z
4      DL  N668DN    LGA  ATL  2013-01-01T11:00:00Z

In [171]:
df.loc[:, df.columns.str.islower()]

   col0  col1  col2  col3  col4  col5       col6
a   0.0   1.0   2.0   3.0   4.0   5.0      apple
b   6.0   7.0   8.0   9.0  10.0  11.0     orange
c  12.0  13.0  14.0  15.0  16.0  17.0  pineapple
d  18.0  19.0  20.0  21.0  22.0  23.0      mango
e  24.0  25.0  26.0  27.0  28.0  29.0       kiwi
f  30.0  31.0  32.0  33.0  34.0  35.0      lemon

In [188]:
base_url = (
    "https://github.com/aeturrell/coding-for-economists/raw/refs/heads/main/data/"
)
state_codes = ["ca", "il"]
end_url = "pop.dta"

# This grabs the two dataframes, one for each state
list_of_state_dfs = [pd.read_stata(base_url + state + end_url) for state in state_codes]
# Show example of first entry in list of dataframes
print(list_of_state_dfs[0])

# Concatenate the list of dataframes
df = pd.concat(list_of_state_dfs, keys=state_codes, axis=1)
df

        county      pop
0  Los Angeles  9878554
1       Orange  2997033
2      Ventura   798364

            ca               il
        county      pop  county      pop
0  Los Angeles  9878554    Cook  5285107
1       Orange  2997033  DeKalb   103729
2      Ventura   798364    Will   673586

In [240]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])

df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])

  letter  number
0      a       1
1      b       2

In [264]:
pd.concat([df1,df2], axis = 0)

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [266]:
pd.concat([df1,df2], axis = 1)

  letter  number letter  number
0      a       1      c       3
1      b       2      d       4

In [268]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})

In [280]:
left = pd.DataFrame(
    {
        "key1": ["K0", "K0", "K1", "K2"],
        "key2": ["K0", "K1", "K0", "K1"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)
right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K1", "K2"],
        "key2": ["K0", "K0", "K0", "K0"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)
# Right merge
pd.merge(left, right, on=["key1", "key2"], how="right")

  key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [284]:
left = pd.DataFrame(
    {
        "key1": ["K0", "K0", "K1", "K2"],
        "key2": ["K0", "K1", "K0", "K1"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)
right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K1", "K2"],
        "key2": ["K0", "K0", "K0", "K0"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)
# Right merge
pd.merge(left, right, on=["key1", "key2"], how="left")

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN